# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4639e8c9e33fe4badd965e769d8b46da"
name = "loyalty cashback store credit"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"


[[webhooks.subscriptions]]
 topics = ["customers/create", "orders/paid"]
 uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_store_credit_account_transactions,read_store_credit_accounts,read_customers,read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
