[[extensions]]
name = "Issue Store Credit"
handle = "issue-store-credit"
type = "flow_action"
uid = "eb971f31-e471-b10a-f5ee-03a13b9b62d5570858d6"
description = "Your description"
runtime_url = "https://west-plymouth-picked-variations.trycloudflare.com/api/flow_triggers"

[settings]

  [[settings.fields]]
  type = "customer_reference"
  required = true

  [[settings.fields]]
  type = "order_reference"
  required = true

  [[settings.fields]]
  type = "single_line_text_field"
  key = "program_id"
  name = "Program ID"
  description = "The ID of the loyalty program"
  required = true