api_version = "2026-04"
uid = "9ebaa5f0-a0d8-25bf-6290-c55f579e4dfac7c7fcd2"

[[extensions]]
type = "ui_extension"
name = "customer-account-ui"
handle = "customer-account-ui"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"
